apiVersion: 1
datasources:
  - { name: Prometheus, type: prometheus, uid: prometheus, url: "http://codeorigin-prometheus:9090", isDefault: true }
  - { name: Loki, type: loki, uid: loki, url: "http://codeorigin-loki:3100" }
